const ONE_SECOND = 1000;

const staleTime = {
	SERVICE: {
		TIP_LIST: {
			PAGE_INFO: ONE_SECOND * 60 * 60,
			ALL_WITH_PAGINATION: ONE_SECOND * 120,
		},
		NEWS_LIST: {
			PAGE_INFO: ONE_SECOND * 60 * 60,
			ALL_WITH_PAGINATION: ONE_SECOND * 120,
			RECENT: ONE_SECOND * 60 * 60,
		},
		REVIEW_LIST: {
			PAGE_INFO: ONE_SECOND * 60 * 60,
			NOTICE: ONE_SECOND * 60 * 60,
			PORTFOLIO: ONE_SECOND * 60 * 60,
			TOTAL_COUNT: ONE_SECOND * 60 * 60,
			ALL_WITH_PAGINATION: ONE_SECOND * 120,
		},
		PRODUCTS: {
			LIST: ONE_SECOND * 60 * 60,
		},
	},
	ADMIN: {
		NEWS_LIST: {
			PAGE_INFO: ONE_SECOND * 60 * 60,
			ALL_WITH_PAGINATION: ONE_SECOND * 120,
		},
		REGISTERED_USER_LIST: {
			PAGE_INFO: ONE_SECOND * 60 * 60,
			ALL_WITH_PAGINATION: ONE_SECOND * 120,
		},
		LEGACY_USER_LIST: {
			PAGE_INFO: ONE_SECOND * 60 * 60,
			ALL_WITH_PAGINATION: ONE_SECOND * 120,
		},
	},

	COURSE: {
		ONLINE_COURSES: {
			ALL: ONE_SECOND * 60 * 60,
		},
		CHAPTERS: {
			ALL: ONE_SECOND * 60 * 60,
		},
		LESSONS: {
			ALL: ONE_SECOND * 60 * 60,
		},
	},
};

export default staleTime;
